### ISSUE TITLE
Compile the file

### ISSUE THREAD

**Issue by Pheeniksu** [manio/mtpass#3]
How do I compile the file? I tried some guides online but I alvays get erors

```
make
g++   -lssl -lcrypto  mtpass.cpp   -o mtpass
/tmp/cc3a19iW.o: In function `cUserRecord::DecryptAndShowRecord()':
mtpass.cpp:(.text._ZN11cUserRecord20DecryptAndShowRecordEv[_ZN11cUserRecord20DecryptAndShowRecordEv]+0xd5): undefined reference to `MD5'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'mtpass' failed
make: *** [mtpass] Error 1
```
Or this:
```
g++ mtpass.cpp -lgnutls-openssl -o mtpass
/usr/bin/x86_64-linux-gnu-ld: cannot find -lgnutls-openssl
collect2: error: ld returned 1 exit status
```
I am running Ubuntu 18.04 
 I am actualy a linux beginner so maybe I am just missing something?

**Comment by manio** [comment]
Hello
Yes, you are missing something. You're trying to do it too fast.
Please read my guide again but slowly and more carefully,
especially a sentence which is beginning with:
"On ubuntu and debian..." :)

**Comment by Pheeniksu** [comment]
If you mean this: On ubuntu and debian the package is called libssl-dev.

I have it installed

**Comment by manio** [comment]
Sorry - I am not using ubuntu, so I cannot help. The error: "undefined reference to `MD5'" is a sign of missing libssl-dev. That's all I know.

Why are you trying to compile it manually against gnutls?
Just type 'make'.

**Comment by Pheeniksu** [comment]
I tried that. It is the first code I posted. If I just type "make" it returns:
```
g++   -lssl -lcrypto  mtpass.cpp   -o mtpass
/tmp/cc3a19iW.o: In function `cUserRecord::DecryptAndShowRecord()':
mtpass.cpp:(.text._ZN11cUserRecord20DecryptAndShowRecordEv[_ZN11cUserRecord20DecryptAndShowRecordEv]+0xd5): undefined reference to `MD5'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'mtpass' failed
make: *** [mtpass] Error 1
```
the other one is a command found somewhere else on the internet

And ubuntu tells me that my libssl-dev is the latest available

**Comment by nbctcp** [comment]
> How do I compile the file? I tried some guides online but I alvays get erors
> 
> ```
> make
> g++   -lssl -lcrypto  mtpass.cpp   -o mtpass
> /tmp/cc3a19iW.o: In function `cUserRecord::DecryptAndShowRecord()':
> mtpass.cpp:(.text._ZN11cUserRecord20DecryptAndShowRecordEv[_ZN11cUserRecord20DecryptAndShowRecordEv]+0xd5): undefined reference to `MD5'
> collect2: error: ld returned 1 exit status
> <builtin>: recipe for target 'mtpass' failed
> make: *** [mtpass] Error 1
> ```
> 
> Or this:
> 
> ```
> g++ mtpass.cpp -lgnutls-openssl -o mtpass
> /usr/bin/x86_64-linux-gnu-ld: cannot find -lgnutls-openssl
> collect2: error: ld returned 1 exit status
> ```
> 
> I am running Ubuntu 18.04
> I am actualy a linux beginner so maybe I am just missing something?

This will fix your issue
# apt install libssl-dev libgnutls-dev libcrypto++-dev
